go1com/util

schema/InstallTrait.php
=> GO1P-12239 Define gc_acces to cache access

report/Export.php
- No need to hide/sort $fields, they are keys of visible fields which have been sorted.
- Headers are now separate parameter.
=> Update report export helper

es/Schema.php, es/mock/EsInstanceMockTrait.php
=> Revert "ES.Lo add instance_version"

contract/ContractHelper.php, lo/LoHelper.php, model/Contract.php
Fix contract price format
Allow more a attributes when filtring Lo description
=> Add ContractHelper::loadActiveContract

group/GroupStatus.php
Change GroupStatus::PRIVATE = 0
=> Change GroupStatus::LOCKED = 2

enrolment/EnrolmentHelper.php
Ref with https://code.go1.com.au/microservices/enrolment/blob/master/controller/create/validate/LearningObjectValidator.php#L204.
Will be tested by https://code.go1.com.au/microservices/enrolment/blob/master/tests/create/EnrolmentSequenceTest.php
=> GO1P-14586 enrolment.helper - Update condition to check completed denpendecies

assignment/AssignmentHelper.php, tests/AssignmentHelperTest.php
=> GO1P-15018 AssignmentHelper - Support locate li.assignment via assignmentId

Service.php, UtilServiceProvider.php, report/Export.php, tests/ReportTest.php
Also fix use allSelected flag (from new report ui)
=> Support exporting report to minio

es/Schema.php
To know when enrollment is created
=> GO1P-14118 Add timestamp to enrollment

payment/TransactionStatus.php
=> Add TransactionStatus class

activity/Activity.php
@drushman Please review my pull request
=> Update code Activity in Util

composer.json
Null coalese operator.
https://github.com/go1com/util/commit/fe285c4572d7ae05398fa3f5e74c52cdf2747261
=> Must use php7

es/Schema.php, es/mock/EsActivityMockTrait.php
@drushman Please review my pull request.
=> GO1P-15355 Update Activity  Schema

activity/Activity.php
@drushman Please review my pull request!
=> Fix Structure Activity

UtilServiceProvider.php
see more here https://github.com/go1com/docker-php/commit/95e219daa4c6a6bc0cf9202ee082342ec10f96be
=> Update Whip definition

Service.php, activity/ActivityRepository.php, es/mock/EsActivityMockTrait.php
@drushman Please review my pull request!
=> GO1P-16497 Implements portal activity feed

activity/ActionType.php, activity/ActivityRepository.php
=> GO1P-16497 Fix getByUserId function

activity/ActivityRepository.php
Please review my pull request! @andytruong @drushman
=> GO1P-16497 Update Sort

activity/ActionType.php
@drushman Please review my pull request!
=> GO1P-16746 Tracking enrollment completion

File.php, composer.json, composer.lock, tests/FileTest.php
This PR do 2 thing:
- Change ````behat/transliterator```` and ````ezyang/htmlpurifier```` from require-dev to require
- Added ````ralouphie/mimey```` and new class File with 2 methods: ````fileName```` and ````fileMimeType````
=> Added File Helper

activity/ActivityType.php
@drushman Please review my merge request!
=> GO1P-16497 Add Class Activity Type

activity/ActivityRepository.php, activity/ActivityType.php
Dear! @drushman Please review my pull request! Thank you!
=> GO1P-16795 Create function get all const in ActivityType

MailTemplate.php
Three templates required for the blue ocean studio
=> BOSSD1-873: add templates for Blue Ocean Studio

es/Schema.php
@drushman Please review my merge quest!
=> GO1P-16861 Update schema for Activity

activity/ActivityRepository.php
@drushman Please review my merge request! Thank you!
=> GO1P-15355 Add condition into query

es/mock/EsActivityMockTrait.php
@andytruong Please view my merge request!
=> GO1P-17387 Add diff property for EsActivityMockTrait

activity/ActionType.php, activity/ActivityType.php
@andytruong Please review my merge request!
=> GO1P-17140 Track masquerading event

activity/ActivityType.php
@andytruong Please review my merge request!
=> GO1P-17397 Use Util ActivityType for Activity

activity/ActivityType.php
@andytruong Please review my pull request! Thank you!
=> GO1P-17021 Tracking contract

clients/MqClient.php, composer.json, composer.lock, tests/clients/MqClientTest.php
@andytruong Please review my merge request!
=> GO1P-17427 No event published after eck.metadata is updated

activity/ActivityType.php
@andytruong Please review my pull request! Thank you!
=> GO1P-17022 Tracking Vote

es/Schema.php, es/mock/EsEnrolmentMockTrait.php
This reverts commit 7a1d31d6aecdcdf527c8e5dc4a77386dbc818bec.
=> Revert "Add certificate (award manual item) to ES LO schema"

activity/ActivityRepository.php
@andytruong Please review my merge request! Thank you!
=> GO1P-17477 Create sort feature for Activity on Staff Page

schema/EnrolmentSchema.php, schema/mock/EnrolmentMockTrait.php
@andytruong Please view my merge request!
=> GO1P-16647 Enrollment revision > Missing enrollment relationship between module/LIs and LOs (course)

schema/mock/EnrolmentMockTrait.php
@andytruong @pvmchau @drushman Please review my merge request! Thank you!
=> GO1P-16647 Enrollment revision - Course have parent_enrolment_id is null instead 0

es/Schema.php, es/mock/EsAwardMockTrait.php, schema/mock/AwardMockTrait.php
- Add AwardEnrolment mock trait
- Update ES enrolment mapping (add last_status)
=> Update ES enrolment mapping (add last_status)

MailTemplate.php
…n's key for due date templates into 3 token's key
=> Add tokens for expiry date reached template. Separate token's key for due date templates into 3 token's key

group/GroupItemTypes.php, group/GroupTypes.php
* Add new group type: enrolment report.
* Add new group type: enrolment report - continue.
=> GroupType > Add report enrolment type (#811)

DB.php, portal/PortalHelper.php
No longer supported in new doctrine version
=> Remove fetch key pair

group/GroupTypes.php
Added a new group type so that v2 of the public API can create a collection as a special group type.
=> GO1P-18923 Add group type "collection"

MailTemplate.php
Add new Mail Template for Event Learner assign course through Group
=> GO1P-18848 Add new Mail Template for Event Learner assign course through Group

MailTemplate.php
@andytruong Please view my merge request! Thank you!
=> GO1P-18848 Mail Template for Award Assign Through Group

schema/CollectionSchema.php, schema/mock/CollectionMockTrait.php, tests/collection/CollectionHelperTest.php
@nguyentodo Please review my merge quest!
=> GO1P-18622 Add status for CollectionSchema

schema/mock/TaskMockTrait.php, task/TaskHelper.php, tests/task/TaskHelperTest.php
Update logic checksum after 1day
=> GO1P-19591: 

customer/CustomerTypes.php, customer/IndustryTypes.php, customer/RegionTypes.php
Add new CustomerTypes, RegionTypes, IndustryTypes
=> GO1P-19592 A GO1 staff can create a customer

queue/Queue.php
=> GO1P-19602 Added queue routing key for usage tracking on customer

contract/ContractBilling.php, contract/ContractInterval.php, contract/ContractStatus.php
=> GO1P-20064: add Interval, Status, Billing attributes to Util

queue/Queue.php
=> GO1P-20069 Add new event name for contract

schema/CreditSchema.php, schema/mock/CreditMockTrait.php
@andytruong Please review my merge request!
=> GO1P-20124 Add new column for Credit

task/TaskHelper.php, tests/task/TaskHelperTest.php
=> GO1P-20460 [#exim] Import - Check previous import task's status when doing checksum

schema/MailSchema.php
Slack discussion from #topic-security: https://go1.slack.com/archives/GDNMSMUAF/p1579845161001400
=> Try to remove html + body from email log

clients/PaymentClient.php, tests/clients/PaymentClientTest.php
PRO-241: add utils to store and retrieve payment customers (payment endpoint)
=> PRO-241: add utils to store and retrieve payment customers (payment endpoint)

clients/EckClient.php, tests/clients/EckClientTest.php
PRO-932: add GET eck fields by entity id method
=> PRO-932: add GET eck fields by entity id method

eck/model/FieldStructure.php
PRO-1376: update EckStructure model to include 'multiselect' property for Staff console forms
=> PRO-1376: update EckStructure model to include 'multiselect' property

EntityTypes.php, eck/model/Entity.php, policy/Realm.php, tests/eck/EckHelperTest.php
- add Realm::EDIT = 3 to policy service
- update eck entity type constants
=> PRO-1579: add Realm::EDIT = 3 to policy; update eck entity type constants

Languages.php, tests/LanguagesTest.php
Ref https://code.go1.com.au/apiom/apiom-ui/-/blob/298730/app/apps/core/services/intl/translation.service.ts#L48
cc @mrsinguyen
=> add Norsk(Bokmål) support to `notify` for Norwegian locales
